version: '3.8'

services:

  # Web Server Service
  notification_nginx:
    image: nginx:alpine
    container_name: notification_nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - notification_service
      - notification_db

  #Database Service
  notification_db:
    image: mysql
    container_name: notification_db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_ROOT_PASSWORD: password

  # Application Service
  notification_service:
    container_name: notification_service
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9001:9000"
    working_dir: /var/www
